Add findSTRINGKnode function
hyginn/BCB420.2019.ESA pull request #18
Opened 2019-03-26 15:05 UTC by rn1n3r

Add exploratory system analysis functionality to investigate the strength of association of vertices in the STRING graph provided by Dr. Steipe to the curated genes provided in the system analysis. Based on work by Cornish & Markowetz (2014) https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003808.

2019-03-31 21:50 UTC, sapirl commented on R/findSTRINGKnodes.R
> +#' findSTRINGKnodes("PHALY", 0.05)
A short explanation for the example is missing

2019-04-01 23:53 UTC, hyginn requested changes
I'm just adding a request-changes tag here, to flag the request as not-quite-ready-yet.

2019-04-05 13:54 UTC, hyginn approved these changes
Some details to be changed after merge

2019-04-05 13:54 UTC, hyginn commented on vignettes/findSTRINGKnodes.bib
> +@misc{steipe-rptPlus,
Merge into one single package bib. Removing this from the fork.

2019-04-05 14:42 UTC, hyginn commented
Hm. Can't resolve deleted Description - merging manually. Closed.

2019-04-05 14:42 UTC, closed without merging