compare Interpro domains of two systems
hyginn/BCB420.2019.ESA pull request #21
Opened 2019-03-29 20:30 UTC by leetina4

…unction

2019-04-01 02:31 UTC, rn1n3r commented on R/symComp.R
> +  # Plot horixontal graph of results
typo: horizontal

2019-04-01 02:36 UTC, rn1n3r commented on R/symComp.R
> +  for (i in seq_along(tmp)) {
Perhaps a comment or two here would help explain what this loop is doing

2019-04-01 02:38 UTC, rn1n3r commented on R/symComp.R
> +symComp <- function(system1, system2) {
Perhaps consider naming the function "sysComp" to make it more clear that it's comparing two systems?

2019-04-01 14:28 UTC, rn1n3r requested changes

2019-04-01 14:28 UTC, rn1n3r commented on R/symComp.R
> +symComp <- function(system1, system2) {
Perhaps consider naming the function "sysComp" to make it more clear that it's comparing two systems?

2019-04-01 14:28 UTC, rn1n3r commented on R/symComp.R
> +  for (i in seq_along(tmp)) {
Perhaps a comment or two here would help explain what this loop is doing

2019-04-01 14:28 UTC, rn1n3r commented on R/symComp.R
> +  # Plot horixontal graph of results
typo: horizontal

2019-04-01 20:53 UTC, sapirl commented on R/symComp.R
> +#' @param system1 The name of the system in interest. Is compared with system2
The @param and @return need to be changed according to the format described here:
https://github.com/hyginn/BCB420.2019.ESA/blob/master/PullRequestReviewNotes.md

The format is: mention the type and dimension of parameters and return values in the header. Type is one of {numeric|integer|double|complex|logical|character|function} ... or a mixed type such as {data frame|list}. The dimension is one of {a|a vector|a matrix|a 3D matrix|...},
For example:
@return (numeric)  A vector of the next six 6-of-49 lottery numbers or NULL.

2019-04-03 02:06 UTC, hyginn commented
Conflict needs to be resolved so Travis can check the package!

2019-04-05 16:01 UTC, hyginn reviewed
Looks oK - but can't really assess without documentation, example runs and interpretation. No Vignette.

2019-04-05 16:01 UTC, hyginn commented
Evaluated as-is. Won't merge. Closed.

2019-04-05 16:01 UTC, closed without merging